### ISSUE TITLE
Would love a version of this for OpenWrt routers

### ISSUE THREAD

**Issue by TTornblom** [lgc-4/one.com-ddns-python-script#2]
OpenWrt based routers supports a variety of ddns services and I would love to see a version of this packaged so that it works on these routers.
At the moment I can run the python script manually on the router, but it would be great to have it integrated.

**Comment by lgc-4** [comment]
I will look into it but I don't think I will be working on it in the near future since this is less of a going on project and more just about providing this script I made to the public.

Maybe you can find a way to automate the script execution such as crontab.

I will leave this issue open, maybe I'll get back to it eventually

**Comment by lgc-4** [comment]
script for openwrt package ddns-scripts has been merged.
